name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up Java 8
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: 8
        cache: "gradle"

    - name: Build Forge mod
      run: chmod +x ./gradlew && ./gradlew clean build --console=plain

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: GlideClient-Forge
        path: build/libs/GlideClient-Forge-*.jar
        if-no-files-found: error
