name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up Java 8
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: 8
        cache: "gradle"

    - name: Build Forge mod (Linux)
      if: runner.os == 'Linux'
      run: chmod +x ./gradlew && ./gradlew clean build --console=plain

    - name: Build Forge mod (Windows)
      if: runner.os == 'Windows'
      run: .\gradlew.bat clean build --console=plain

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: GlideClient-Forge-${{ runner.os }}
        path: build/libs/GlideClient-Forge-*.jar
        if-no-files-found: error
